### ISSUE TITLE
is variables() call on builder really necessary?

### ISSUE THREAD

**Issue by farfromrefug** [fasseg/exp4j#22]
I am wondering if the call to variables() for variables is really necessary.

My problem is that my variables are stored in a HashMap.

So if i want to respect the current way defining and setting variables then i need to go through my hashmap twice:
* once to call variables 
* then i build the Expression
* a second to set the variables values. 

Seems a little overkill :s
Is there's a way around this?

Thanks

**Comment by fasseg** [comment]
I guess we could implement this and make it perfectly clear in the API Doc that it's a convenience method and variables can and should still be set after the call to `ExpressionBuilder.build()`, when reevaluating the same expression with different variable values.
 What do you guys think?

**Comment by farfromrefug** [comment]
@fasseg do you mean that it should be like this?
```
MathExpr mExpr = new MathExpr.MathExprBuilder("3 * sin(y) - 2 / (x - 2)")
                .build();
        double result2 = mExpr
                .variable("x", 2.3)
                .variable("y", 3.14)
                .evaluate();
```
If so it seems great!

**Comment by fasseg** [comment]
@farfromrefug Not exactly since all variables have to be declared in order to successfully call `build()`.
What I meant was something like this:

```
Expression e = new ExpressionBuilder("sin(x)")
                                     .variable(x, 1)
                                     .build();
double res1 = e.evaluate();
double res2 = e.setVariable("x", 2)
                         .evaluate();
```

And the Javadoc for `ExpressionBuilder.variable(String name, double default)` should read something like this:

*A convenience method to declare and initialize a variable with a default value. Be aware that for subsequent variable changes you should use Expression.setVariable(String name, double val), since the ExpressionBuilder.build() is a heavy operation.*

**This is bad**: Two calls to ExpressionBuilder.build() for changing a variable:
```
double res1 = new ExpressionBuilder("sin(x)")
                               .variable("x", 1)
                               .build();
double res2 = new ExpressionBuilder("sin(x)")
                               .variable("x", 2)
                               .build(); 

```
**Better**: One call to ExpressionBuilder.build() only:
```
Expression e = new ExpressionBuilder("sin(x)")
                               .variable("x", 1)
                               .build();
double res1 = e.evaluate();
double res2 = e.setVariable("x",2)
                         .evaluate();
```

**Comment by farfromrefug** [comment]
Well it does not fix my problem :s Still have to loop all the variables twice. Seems overkill to me.

**Comment by fasseg** [comment]
Sorry that was unclear, but the ExpressionBuilder would have a variables(Map<String, Double> vars) method then, which could be used:
```
double result = new ExpressionBuilder("sin(x*y/z)")
                               .variables(myVarMap)
                               .build()
                               .evaluate();
```

BTW you already do this (no iteration on your side):
```
Map<String, Double> myvars = new HashMap<String, Double>;
myvars.put("x", 12);
myvars.put("y",7);

Expression e = new ExpressionBuilder("sin(xy)")
  .variables(myvars.keySet())
  .build();

double result = e.setVariables(myvars)
  .evaluate();
```

But there's no way to remove variable declaration before the build() step. Since this information is needed for tokenization.

**Comment by leogtzr** [comment]
I agree with @fasseg , doing so would break a little the purpose of the Builder pattern.

**Comment by farfromrefug** [comment]
@leogtzr @fasseg i totally understand! And i like your way of doing it with a Hashmap. 
Though it s still a "double" loop as one is done in the "variables()" and one in the "setVariables".
Still seems overkill to me ;)

Thanks

**Comment by fasseg** [comment]
@farfromrefug 
As elaborated, there's now way feasible, safe and performant way to merge variable declaration and variable manipulation.
