### ISSUE TITLE
Feature request to take in a number format

### ISSUE THREAD

**Issue by vandanagopal** [fasseg/exp4j#24]
In our application we have a requirement that any double value in an equation is converted using a number format.
Example:
format = NumberFormat.getInstance()
Number number = numberFormat.parse(value);
retVal = number.doubleValue();
Using exp4j, it would be nice if the evaluate function accepted a NumberFormat which it would use to convert every double value during the calculation process.

**Comment by fasseg** [comment]
Hmm I'll have to take a look at that, but I'm quite sure that using e.g. a german NumberFormat (a comma instead of a dot as a decimal separator) will break exp4j, since there's no way to distinguish between a argument separator and a decimal separator.
E.g.:
log(3,4)
There's no way to decide if this is the log of 3 to the base 4 (2 arguments) or the natural logarithm of 3.4 (only a single argument)

But I'm of course open to suggestions...

**Comment by vandanagopal** [comment]
Ahh ok yes I see that would unnecessarily complicate matters. No problem, found that the NumberFormat is no longer necessary in my project so I don't need the NumberFormat anymore. Thanks.
