### ISSUE TITLE
Feature request to support mathematical constants

### ISSUE THREAD

**Issue by zvory** [fasseg/exp4j#32]
e -> Math.E
π or "pi" (or \u03C0 ) -> Math.PI
φ -> 1.61803398874

This can be done by the person using the library by setting variables but it should be a default, these arent variable.

**Comment by fasseg** [comment]
I am not sure that this feature can be implemented just by adding some constant identifiers, since existing software using exp4j might use the characters for variables or functions. This might lead to some unexpected behaviour and in the worst case to regressions:

In the following case `e` might get ambigious. Do we just overwrite the constant value? Throwing an exception is IMHO not an option since existing software might break:
```Java
new ExpressionBuilder("sin(e)")
    .variables("e")  // What to do here?
    .build()
    .setVariable("e", 0);
```

Another issue I might see arise from this is a lot more requests for constant values. A chemist might want the avogrado number as a constant value in exp4j

Maybe we can think about different subclasses of ExpressionBuilder concerned with different subjects:
```Java
ExpressionBuilder b = new PhysicsExpressionBuilder("G*m1*m2/r^2")
                                               .variables("m1,"m2","r")
                                               .build();
```

but I would not want to touch the current implementation and I fear we open pandora's box ;)

What do you guys think of this feature?
I know @leogtzr  did some work on this in: https://github.com/leogtzr/exp4j/commit/4910cf6f6775abfabb0d41118c819ea69cc3d49c

**Comment by zvory** [comment]
Well come things are always constant and are never used elsewhere.
π will never be used as anything but 3.1415... .
But I guess you are right, in other cases we can have ambiguity.
I suppose if e is set as a varibale it will be over-ridden by user input, but if e is not specified as a variable any instances of e will by default evaluate to 3.1415? Something like this makes sense to me, but there could still be issues.

**Comment by fasseg** [comment]
@zvory:
I certainly think that overwriting shouldn't be a problem, but Im not a hundert percent sure.
@leogtzr, @dktcoding: What d you guys think about this feature? Can you think of san instance where this will break existing code?

**Comment by dktcoding** [comment]
I can think of several instances where using symbols may break existing code, there are a couple of constants that are universal, like π, but who's to say what precision is currently being used by apps relying on exp4j.

I think a perhaps more prudent approach is to implement constants as zero-argument functions (pi(), e(), true(), false(), etc()) in which case there's no need to change any actual code and even the simplifier will work. 

We just need to make sure that user-defined functions are evaluated before built-in functions (this _should_ take care of the overriding).

**Comment by fasseg** [comment]
Numerical constants (pi, e, phi) have been added to master branch, see https://github.com/fasseg/exp4j/pull/33
