### ISSUE TITLE
Suggestion on Simplification

### ISSUE THREAD

**Issue by nathanielove** [fasseg/exp4j#34]
Personally I have tried wrapping your `Expression` class into an `EasyExpression` class, so that creating and evaluating a simple expression can be a lot easier. For example, 

```java
EasyExpression exp = EasyExpression.of("3x^2 + 2*asin(y) + ln(z)", "x", "y", "z" );
double result = exp.evaluate(3.4, 5, 7);
```

In the example above, there's no need to use the builder, or to call a lot different methods like ```setVariable()```, or ```setVariables()```. The values in the parameters of the ```evaluate()``` method must follow the same order as they were specified upon creation using ```of()```. But this is usually not a problem because common variables in an expression are just like "a,b,c" or "x,y,z", sometimes "u,v,w". Even though they might not be neighboring letters in the alphabet, it's still easy to sort them up alphabetically when creating an expression.

One more thing about the `EasyExpression` - more functions, including all in the `java.lang.Math` class, are built-in for every object created by default.

Also for the `Function` class, I've wrapped it up into a `SafeFunction`, with enforced parameter checking. For example, the `sin()` function is supposed to have only one parameter. If a user passes in 2 parameters by accident, an `IllegalArgumentException` will be thrown.

Anyway, I'm not saying that I wanna overthrow whatever is already in this library, like the `ExpressionBuilder`. But, there should be some extension to this library so that the users who only wish  to create some simple expressions won't have to go through such a long & complicated procedure.

Again, keep the powerful features for the users with complex tasks, but do provide an express way for the users who don't need that much.

BTW, how often do you think users would really define their own operators and functions?

**Comment by fasseg** [comment]
@nathanielove: Thanks for the input on your `EasyExpression.`
I have to say I am reluctant to add thi feature again (as it was part of exp4j < 0.4). The problem I see and lots of people had with this approach is that they forgot about the ordering and tried e.g. alphabetical ordering, although the featture was clearly documented in the Javadoc.

It's definetely better to have this feature outsorced into an `EasyExpression` class but I fear people will fall in the same pitfalls again.

As for the `SafeFunction`: I really like this, and I am a little bit unsure why it's not part of the existing builtin functions. Do you wanna add this check to `Functions.java` and send me a PR?

**Comment by leogtzr** [comment]
I like the idea, but maybe we need to think in something less error-prone
```java
EasyExpression exp = EasyExpression.of("3x^2 + 2*asin(y) + ln(z)").var("x", 3.4).var("y", 5).var("z", y);
```
But I suppose this also looks some complex/long as @nathanielove stated.

**Comment by nathanielove** [comment]
First, thank you both for your reply. 

Well I've already implemented both `EasyExpression` and `SafeFunction` last winter. But I can't really refine them now coz I got final exams in about 2 weeks. I'll send you a copy after the exams.

**Comment by dktcoding** [comment]
```EasyExpression``` seems like a nice idea (I remember writing a class like that when I first started with ```exp4j```). 
The problem I see besides the order of the variables named by @fasseg is that the current approach is great when working when dynamic inputs (```setVariable()``` might seem like an overkill at first sight, but it's very loopable; besides ```varargs``` need to have a fixed length on compile time). That being said, I like the idea of ```EasyExpression``` for compile time expressions.

```SafeFunction``` is a great idea, but I think it might be better to handle this from the builder, since an ```Expression``` with the wrong number of arguments in a function should never pass the building phase. The current builder code doesn't check # of arguments, and the exception is raised only when ```Expression#evaluate()``` is called...... we should fix this..... I don't see any easy answer for this....

@fasseg Even ```Expression#validate()``` fails here, since it checks for _enough_ arguments but not for an [exact match](https://github.com/fasseg/exp4j/blob/master/src/main/java/net/objecthunter/exp4j/Expression.java#L95)

**Comment by fasseg** [comment]
We wont be fixing this then, it raises way too many issues and we will rely on Users to write their own handlers for this kind of functionality then.
