### ISSUE TITLE
Validation failed when function has 2 parameters

### ISSUE THREAD

**Issue by laupping** [fasseg/exp4j#40]
Hi,
Validation will failed when the function has 2 parameters,  the following code will return "Too many operands" error
```
    	Expression e = new ExpressionBuilder("pow(A,B)")
    		.variables("A")
    		.variables("B")
    		.build();

		ValidationResult res = e.validate(false);
```

**Comment by fasseg** [comment]
Will take a look at this. Thanks for the report

**Comment by sarxos** [comment]
Hi @laupping,

FYI, this problem has been already fixed by d2e63418c76ff08cc290e795bd13f2344a57c2a6 as #36 and released by @fasseg in the [0.4.5](http://search.maven.org/#artifactdetails|net.objecthunter|exp4j|0.4.5|jar). I tested your code on the mentioned version and the result is valid. There is no _"too many operands"_ error as observed prior 0.4.5 release.

```java
Expression exp = new ExpressionBuilder("pow(A,B)")
	.variables("A")
	.variables("B")
	.build();
boolean valid = exp
	.validate(false) // only null result on the validation list
	.isValid()); // true
```

**Comment by laupping** [comment]
Thanks @sarxos , I was testing on 0.4.4. Release 0.4.5 works fine.

**Comment by fasseg** [comment]
Closed as fixed.
