### ISSUE TITLE
Calculation problem

### ISSUE THREAD

**Issue by kschang009** [fasseg/exp4j#52]
Multiply two integer, then divide by either one of the integer, result is a 15 decimal places number

**Comment by sarxos** [comment]
Hi @kschang009, since exp4j uses ```double``` types the result in some cases may be different than you expect. Different value result is due to binary divide/multiplications where least significant bit is rounded down when divided.

**Comment by kschang009** [comment]
Please tell me how to solve the problem?  
For example, 123,456789012346 x 10 = 1234.5678901234598, it seems odd. 8(

**Comment by fasseg** [comment]
Hola @kschang009, 

This is due to the way that computers handle floating point numbers. May be you want to read up on https://en.wikipedia.org/wiki/Floating_point.
E.g. look at the following plain java code:

```
public class FPMathExample {
    public static void main(String[] args) {
        System.out.print(123.456789012346d * 10d);
    }
}
```

This does also print out "1234.5678901234598" since floating point representation are not exact.

**Comment by kschang009** [comment]
Is it possible to limit results to 14 decimals as I found that can solve
most problems, and the  results will look more accurate.

Thank you for your help. 8)
