### ISSUE TITLE
Problem with simple sum accounts

### ISSUE THREAD

**Issue by caiocrol** [fasseg/exp4j#55]
Hi i discovered the exp4j and i'm really interested but i´m facing a problem with simple accounts.
like this one 1.2+2.2 the result is always 3.4000000000000004 could it be a bug or there is a way to solve this?

**Comment by sarxos** [comment]
Hi @caiocrol,

This is not a bug. This is how floating point arithmetic works in Java (and many other programming languages).

Check this code:

```java
public class Arithmetic {
	public static void main(String[] args) {
		System.out.println(1.2 + 2.2);
	}
}
```

It outputs:

```plain
3.4000000000000004
```

This is because of the floating point numbers [finite precision](https://en.wikipedia.org/wiki/Floating_point#Accuracy_problems) resulting from binary operations on finite bit sets used to store both mantissa and exponent.

**Comment by caiocrol** [comment]
Thank's for your answer, i solved by puting a decimal format on my number.

`
DecimalFormatSymbols otherSymbols = new DecimalFormatSymbols(Locale.ENGLISH);
DecimalFormat decimalFormat = new DecimalFormat( "###,###.########" , otherSymbols );
decimalFormat.format(Double.parseDouble(cBeforeDot));
`
