### ISSUE TITLE
Errors with validation

### ISSUE THREAD

**Issue by stackkian** [fasseg/exp4j#70]
Hello, 

I am noticing some odd behavior when running the validation method. When I have an equation such as "x ++++ 6" it resolves it as being a valid expression. Additionally, I have seen it resolve "x 100" as being true. It seems as though these shouldn't be valid expressions. 

Thanks, 

Kian

**Comment by dktcoding** [comment]
Hello,

Both of those expressions are actually valid.

- `x +++++ 6` or even `x +-+-+--++ 6` are valid expressions, because both the `+` and the `-` operator can be binary or unary operators, so `x +++++ 6` will be interpreted as `x+(+(+(+(+6))))`
- About `x 100` if you are using version 4 you are looking at the effects of implicit multiplication even `x100` will be interpreted as `x*100`. There's currently a branch (a73e3cd8202fdc75498bc9d3fdd5450ab682c7b1) which allow disabling implicit multiplication, but we should wait for @fasseg to see if it's ready and when/if it's eventually going to get merged to master.

Regards

**Comment by fasseg** [comment]
Hey Guys, 
I do have January off and will invest some time to get exp4j up to date. Unfortunately I do not have enough time to do this properly earlier...

**Comment by fasseg** [comment]
Merged https://github.com/fasseg/exp4j/commit/a73e3cd8202fdc75498bc9d3fdd5450ab682c7b1 into master.
@stackkian: You are now allowed to turn off implicit multiplication and the validator returns `false`:
```
    @Test(expected = IllegalArgumentException.class)
    public void testImplicitMulitplicationOffVariable() throws Exception {
        Expression e = new ExpressionBuilder("var_1var_1")
                .variable("var_1")
                .implicitMultiplication(false)
                .build();
        e.evaluate();
    }
```
