### ISSUE TITLE
Trigonometric functions in degrees.

### ISSUE THREAD

**Issue by a35joshi** [fasseg/exp4j#72]
Not sure if we have this but can we please add the ability to perform trigonometric calculations such as sin,cos, tan etc in degrees too? Right now it is only radians I believe.

**Comment by dktcoding** [comment]
Hi there

There's a very low chance (if at all) of that happening, since all if not most calculations and specifications are actually done in radians (a little thing call [International System of Units](https://www.nist.gov/sites/default/files/documents/pml/div684/fcdc/sp330-2.pdf)).

But you could a) implement the full set of functions, b) simply add a couple of functions called deg2rad and rad2deg (or whatever you want to call them), or c) transform your angles before calling `exp.setVariables()`.

```Java
    Expression exp = new ExpressionBuilder("sin(deg2rad(90))").function(new Function("deg2rad") {
        @Override public double apply(double... args) {
            return args[0] * Math.PI / 180;
        }
    }).build();
```

That code should work (I' can't test it now), and return 1 instead of... whatever the sin of 90 rads evaluates to (?).

Regards!

**Comment by a35joshi** [comment]
Hi.


Thank you for your reply. But I had a couple of questions and I am having difficulty in parsing the information you provided.

I am making a scientific calculator and I wanted to include trigonometric functions with inputs in degrees. I did not quite understand your suggestion c) because I do not really use exp.set_variable. My calculator takes a string from the screen like say sin(cos(45)) and evaluates it in this manner:

String expressiontoevaluate = output.getText().toString();
    Expression expression = new ExpressionBuilder(expressiontoevaluate).build();
    double result = expression.evaluate();
    output.setText(Double.toString(result));

Where should I be using the set_variable syntax? This returns an answer in radians but I want degrees as I mentioned.

Also if I use the method you gave it will work if there is just one variable like sin(90) or so but it gives me an error when I do sin(cos(90)) or something like that.

Am I missing something here?

Await your suggestions.

Thank You!

Anurag Joshi.
________________________________

**Comment by dktcoding** [comment]
Ahhh ok, (context is important in questions)

In that case (since you aren't using variables), perhaps the easiest way is to use something like `rad2deg` and `deg2rad` (particularly since in a scientific calculator you'll want such functions).

If your idea is to copy the `String` directly into `ExpressionBuilder`, you might as well override the functions to receive an argument in degrees like in 48c16aa37ebc5521bb3e42b1396507354e24534d (the commit you submitted), `exp4j` parses user-defined functions first, so if you redefine all the trigonometric functions in degrees, you shouldn't encounter any problem.

That being said, you should also remember that there are a LOT of trigonometric functions, and also the inverse trigonometric functions should be adapted to return angles in degrees (`asin`, `acos`, etc.).

The _cleanest_ approach to doing so is (in my opinion) create a `Function` array and simply pass the array to `ExpressionBuilder` for example:

```Java
    private Function[] myFunctions = {
        new Function("sin"){public double apply(double... args){return Math.sin(Math.toRadians(args[0]));}},
        new Function("cos"){public double apply(double... args){return Math.cos(Math.toRadians(args[0]));}},
        //etc...
    }

    public void evaluate() {
        String expressiontoevaluate = output.getText().toString();
        Expression expression = new ExpressionBuilder(expressiontoevaluate).functions(myFunctions).build();
        double result = expression.evaluate();
        output.setText(Double.toString(result));
    }
``` 

As an aside, checkout methods like `Expression#validate()` and things like `ValidateResult` in order to tell your users if the expression is valid or not.

More info is available in the [`exp4j` webpage](http://www.objecthunter.net/exp4j/).

Regards

**Comment by a35joshi** [comment]
Hi.

Thank You for your reply and your recommended method. I was successfully able to implement this method! So, thank you once again.

As you mentioned, I tried using the inverse trigonometric functions earlier and it worked in case of a single trigonometric function like say just sin45. However in cases such as sin(cos(45)) or so it used to output the wrong result and hence I had to scrap that idea.

However, the method you gave works perfectly.

Thank You!
