### ISSUE TITLE
BigDecimal version

### ISSUE THREAD

**Issue by dilworks** [fasseg/exp4j#84]
Hi there!

First things first: thank you for this great expression evaluation library! So far it has been working wonders in my product (a custom payroll system), although I've yet to exploit it to its full potential (for example, defining custom functions).

However, there is a little yet annoying detail that can be an dealbreaker for anyone relying on exp4j for calculating anything involving currency: see, exp4j defaults to Double, but when involving money, Double and its friends are a really _really_ bad idea due to its (excess of) precision - it's extremely easy to fall into the typical trap of rounding errors. Beancounters HATE things like 2-cent differences due to rounding errors with the passion of 1000 burning suns, and this quickly devolves into a living hell for both developers and customers.

The solution to this dilemma is BigDecimal, where we can work with arbitrary precision - for the typical currency case, just set it to 2 decimal digits, pick a sane rounding mode, and that way you can keep beancounters quiet... for a while. Although you can wrap the results of Expression.evaluate() into a new BigDecimal object, it would be nice for exp4j to offer native support for BigDecimal calculations, to be in control of precision since the very beginning.

How feasible would it be a native BigDecimal version?

**Comment by fasseg** [comment]
Hey dilworks, unfortunately this is out of scope for exp4j. But maybe scaling the numbers up to your required precision will help.

Have fun!

Frank

**Comment by dilworks** [comment]
Ah well... At least wrapping Doubles into BigDecimals and setting precision there is a reasonable workaround for now.

Anyway, thanks for your reply!

**Comment by kainjinez** [comment]
@dilworks Hi dilworks. Do you have any idea to fix this? If yes, can you give an example? Thanks.

**Comment by dilworks** [comment]
@kainjinez 
You want something like this:

`ExpressionBuilder eb = new ExpressionBuilder("your+formula-goes-here");
// Do your expression build stuff here
Expression exp = eb.build();
BigDecimal ret = new BigDecimal(exp.evaluate());
ret.setScale(2, RoundingMode.HALF_UP);`

Since we're dealing with currency, most likely you will want to work with a scale of 2 (two decimals), and rounding using the half-up rule (example: 0.044 => 0.04, 0.045 => 0.05). However, care should be exercised when dealing with variables and custom functions to prevent rounding errors.

**Comment by metalhead44** [comment]
@dilworks so you are just concerned about using BigDecimal for the result. All other operations inside would be performed on double and that would not cause any issue?

**Comment by RobertZenz** [comment]
> Since we're dealing with currency...

Since you are dealing with currency you ***never, ever, I really mean never,*** want to use float or double. You're begging for trouble if you do. You either use ints/longs with a well defined behavior when rounding is needed (f.e. `10 / 3`) or you use `BigDecimal` with a well defined behavior when rounding is needed.

**Comment by metalhead44** [comment]
I don't think I expressed myself correctly. @RobertZenz The current api uses double for all the calculations and as per your comment , I totally agree that bigdecimal should be the way for money calcluations. All am asking is if we just convert the result (exp.evaluate()) using a BigDecimal Wrapper like you cited above in the comment, would we be safe enough considering the framework still uses double values within the expression for all its calculations. Your approach is just converting the result in to BigDecimal and I am not sure if that is sufficient.
I think the existing codebase cannot support BigDecimals because the oerations on BigDecimal is not overloaded, so double is used. I wish if the authors can explain with examples or some citations when to use this library and where it can cause issues especially when used in production and dealing with monetary calculations.

**Comment by RobertZenz** [comment]
> All am asking is if we just convert the result (exp.evaluate()) using a BigDecimal Wrapper like you cited above in the comment, would we be safe enough considering the framework still uses double values within the expression for all its calculations. Your approach is just converting the result in to BigDecimal and I am not sure if that is sufficient.

That is not sufficient in any way, for your information. The moment you do *one* calculation in `double`/`float` you're screwed. True, it is not that grim, there is a good chance that everything turns out to be okay...but may whatever deities you believe in have mercy on your soul if it goes not okay, because then you'll find yourself in a world of pain.

 > I wish if the authors can explain with examples or some citations when to use this library and where it can cause issues especially when used in production and dealing with monetary calculations.

The use case for this library is simple: Whenever double precision is sufficient. Graphics, many areas of calculations, applications providing custom mathematical support, etc.

If you need a library which uses `BigDecimal`s, you can turn to to something like [EvalEx](https://github.com/uklimaschewski/EvalEx). Which, obviously, comes with its own drawbacks (possible slower execution speed, higher object creation cound, etc.).

**Comment by dilworks** [comment]
@RobertZenz : You're right - when dealing with money, Double/Float is right out of the question... but sometimes you have no choice but to deal with it, damned be the consequences

So far, on the payroll application where I've implemented exp4j, wrapping the final result in BigDecimal has been Good Enough™ for us (leaving aside the occasional rounding error which leads to one-cent mismatches and very angry beancounters), but as you've pointed out, this gets unsustainable for long-term usage if you actually care about precision for currency calculations.

I've been checking the code - it doesn't look THAT hard to move everything from Double to BigDecimal. The biggest question would be where to tackle the usage of MathContext/RoundingMode so the relevant methods can work with the desired precision level. If I find some free time, I'll play with that...

Also, thanks for the suggestion of EvalEx - I'll check it out as having a plan B/C is always great.

**Comment by RobertZenz** [comment]
> ...wrapping the final result in BigDecimal has been Good Enough™ for us (leaving aside the occasional rounding error which leads to one-cent mismatches and very angry beancounters)...

I know we are entering nitpicky territory here, but that doesn't sound like it is "good enough" for you, to be honest.

 > The biggest question would be where to tackle the usage of MathContext/RoundingMode so the relevant methods can work with the desired precision level

EvalEx sets it for the whole expression which will be evaluated, which means that every operation inside the expression is performed with that context and rounding. Which yields reproducible results as far as I am aware. Keep in mind that internally you can only use so much precision (f.e. `1/3`) before it blows up. So I guess that approach is quite acceptable. If somebody requires the operation to be performed with a higher precision, they can set set that higher precision and round the result afterwards accordingly.

Also keep in mind that every `BigDecimal` does know its context and rounding mode, so operation invoked from that instance will use that by default.
