### ISSUE TITLE
number end with"%"

### ISSUE THREAD

**Issue by yigaohui** [fasseg/exp4j#97]
Hello friend:
         the exp4j can't work well when the expression like "(1.88177*0.74)/(1870.211000% *1000)"What should I do?
Looking forward to your reply,thanks

**Comment by sarxos** [comment]
You mean the use of modulo operator `%` sign? Just by looking at the example it seems to be invalid because both `%` and `*` multiplicative operators requires two operands to be present and you provided only one, so expression like this:

```1870.211000 % * 1000```

Is incorrect, not only in `exp4j`, but in classic mathematics as well. You need to add missing operand, e.g. lets put a value `7` there and it will be valid again:

```1870.211000 % 7 * 1000```

**Comment by yigaohui** [comment]
thanks, I have solved the problem,in my App, the "%" can not work as  modulo operator , it just work as a symbol mark percentage

**Comment by sarxos** [comment]
@yigaohui I'm glad you fixed the probklem. Please close this ticket then so we do not left unnecessary issues open :)
